// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaaS.Veterinario.Infrastructure.Persistencia;

#nullable disable

namespace SaaS.Veterinario.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SaaSVeterinarioDbContext))]
    [Migration("20260906050910_AddClientesAndPets")]
    partial class AddClientesAndPets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_identidad_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_identidad_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuarios_identidad_tokens", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Clientes.ClienteVeterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeterinariaId")
                        .HasDatabaseName("ix_clientes_veterinaria_veterinaria_id");

                    b.ToTable("clientes_veterinaria", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_especies_codigo_unico");

                    b.ToTable("especies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Codigo = "PERRO",
                            Estado = "ACTIVO",
                            Nombre = "Perro"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Codigo = "GATO",
                            Estado = "ACTIVO",
                            Nombre = "Gato"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Codigo = "AVE",
                            Estado = "ACTIVO",
                            Nombre = "Ave"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            Codigo = "CONEJO",
                            Estado = "ACTIVO",
                            Nombre = "Conejo"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            Codigo = "OTRO",
                            Estado = "ACTIVO",
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.Mascota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_publico");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid")
                        .HasColumnName("especie_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<bool?>("Esterilizado")
                        .HasColumnType("boolean")
                        .HasColumnName("esterilizado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<bool>("FechaNacimientoAproximada")
                        .HasColumnType("boolean")
                        .HasColumnName("fecha_nacimiento_aproximada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroMicrochip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_microchip");

                    b.Property<Guid?>("RazaId")
                        .HasColumnType("uuid")
                        .HasColumnName("raza_id");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPublico")
                        .IsUnique()
                        .HasDatabaseName("ix_mascotas_codigo_publico_unico");

                    b.HasIndex("EspecieId");

                    b.HasIndex("NumeroMicrochip")
                        .IsUnique()
                        .HasDatabaseName("ux_mascotas_numero_microchip")
                        .HasFilter("numero_microchip IS NOT NULL");

                    b.HasIndex("RazaId");

                    b.ToTable("mascotas", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.MascotaVeterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("MascotaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mascota_id");

                    b.Property<string>("NumeroHistoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_historia");

                    b.Property<string>("ObservacionesInternas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones_internas");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("VeterinariaId", "MascotaId")
                        .IsUnique()
                        .HasDatabaseName("ux_mascotas_veterinaria_veterinaria_mascota");

                    b.ToTable("mascotas_veterinaria", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.Raza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid")
                        .HasColumnName("especie_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_razas_especie_nombre");

                    b.ToTable("razas", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.ResponsableMascota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteVeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_veterinaria_id");

                    b.Property<string>("Correo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoVinculacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_vinculacion");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("MascotaVeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mascota_veterinaria_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<bool>("PuedeGestionarTratamientos")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_gestionar_tratamientos");

                    b.Property<bool>("PuedeVerHistorial")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_ver_historial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_relacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteVeterinariaId");

                    b.HasIndex("MascotaVeterinariaId")
                        .IsUnique()
                        .HasDatabaseName("ux_responsables_mascota_principal_activo")
                        .HasFilter("es_principal AND estado = 'ACTIVO'");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeterinariaId")
                        .HasDatabaseName("ix_responsables_mascota_veterinaria_id");

                    b.ToTable("responsables_mascota", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaRol", b =>
                {
                    b.Property<Guid>("MembresiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("membresia_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("MembresiaId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("membresias_roles", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UsuarioId" }, "ix_membresias_veterinaria_usuario_id");

                    b.HasIndex(new[] { "VeterinariaId" }, "ix_membresias_veterinaria_veterinaria_id");

                    b.HasIndex(new[] { "UsuarioId" }, "ux_membresias_veterinaria_usuario_activa")
                        .IsUnique()
                        .HasFilter("estado = 'ACTIVA'");

                    b.ToTable("membresias_veterinaria", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Permisos.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_codigo_unico");

                    b.ToTable("permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Codigo = "veterinaria.ver",
                            Nombre = "Ver veterinaria"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Codigo = "veterinaria.editar",
                            Nombre = "Editar veterinaria"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Codigo = "personal.ver",
                            Nombre = "Ver personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Codigo = "personal.invitar",
                            Nombre = "Invitar personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Codigo = "personal.editar",
                            Nombre = "Editar personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Codigo = "personal.finalizar",
                            Nombre = "Finalizar personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            Codigo = "clientes.ver",
                            Nombre = "Ver clientes"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            Codigo = "clientes.crear",
                            Nombre = "Crear clientes"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            Codigo = "clientes.editar",
                            Nombre = "Editar clientes"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            Codigo = "mascotas.ver",
                            Nombre = "Ver mascotas"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000011"),
                            Codigo = "mascotas.crear",
                            Nombre = "Crear mascotas"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000012"),
                            Codigo = "mascotas.editar",
                            Nombre = "Editar mascotas"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000013"),
                            Codigo = "responsables.ver",
                            Nombre = "Ver responsables"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000014"),
                            Codigo = "responsables.crear",
                            Nombre = "Crear responsables"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000015"),
                            Codigo = "responsables.editar",
                            Nombre = "Editar responsables"
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Personal.InvitacionPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aceptacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitaciones_personal_token_hash_unico");

                    b.HasIndex("VeterinariaId")
                        .HasDatabaseName("ix_invitaciones_personal_veterinaria_id");

                    b.HasIndex("VeterinariaId", "Correo")
                        .IsUnique()
                        .HasDatabaseName("ux_invitaciones_personal_veterinaria_correo_pendiente")
                        .HasFilter("estado = 'PENDIENTE'");

                    b.ToTable("invitaciones_personal", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Personal.InvitacionPersonalRol", b =>
                {
                    b.Property<Guid>("InvitacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitacion_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("InvitacionId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("invitaciones_personal_roles", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo_unico");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Codigo = "ADMINISTRADOR_VETERINARIA",
                            Estado = "ACTIVO",
                            Nombre = "Administrador de veterinaria"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Codigo = "VETERINARIO",
                            Estado = "ACTIVO",
                            Nombre = "Veterinario"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Codigo = "ASISTENTE",
                            Estado = "ACTIVO",
                            Nombre = "Asistente"
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000015")
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_verificado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<bool>("TelefonoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("telefono_verificado");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo_unico");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_publico");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Ruc")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPublico")
                        .IsUnique()
                        .HasDatabaseName("ix_veterinarias_codigo_publico_unico");

                    b.ToTable("veterinarias", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Infrastructure.Identidad.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("dispositivo");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTimeOffset?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash_unico");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Infrastructure.Identidad.UsuarioIdentidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_identidad_usuario_id_unico");

                    b.ToTable("usuarios_identidad", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SaaS.Veterinario.Infrastructure.Identidad.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SaaS.Veterinario.Infrastructure.Identidad.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SaaS.Veterinario.Infrastructure.Identidad.UsuarioIdentidad", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Clientes.ClienteVeterinaria", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.Mascota", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Mascotas.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Mascotas.Raza", null)
                        .WithMany()
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.MascotaVeterinaria", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Mascotas.Mascota", null)
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.Raza", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Mascotas.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Mascotas.ResponsableMascota", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Clientes.ClienteVeterinaria", null)
                        .WithMany()
                        .HasForeignKey("ClienteVeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaaS.Veterinario.Domain.Mascotas.MascotaVeterinaria", null)
                        .WithMany()
                        .HasForeignKey("MascotaVeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaRol", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", null)
                        .WithMany("Roles")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Personal.InvitacionPersonal", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Personal.InvitacionPersonalRol", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Personal.InvitacionPersonal", null)
                        .WithMany("Roles")
                        .HasForeignKey("InvitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.RolPermiso", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Permisos.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Roles.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Infrastructure.Identidad.RefreshToken", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Infrastructure.Identidad.UsuarioIdentidad", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Personal.InvitacionPersonal", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.Rol", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
