// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaaS.Veterinario.Infrastructure.Persistencia;

#nullable disable

namespace SaaS.Veterinario.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SaaSVeterinarioDbContext))]
    partial class SaaSVeterinarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaRol", b =>
                {
                    b.Property<Guid>("MembresiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("membresia_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("MembresiaId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("membresias_roles", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinaria_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UsuarioId" }, "ix_membresias_veterinaria_usuario_id");

                    b.HasIndex(new[] { "VeterinariaId" }, "ix_membresias_veterinaria_veterinaria_id");

                    b.HasIndex(new[] { "UsuarioId" }, "ux_membresias_veterinaria_usuario_activa")
                        .IsUnique()
                        .HasFilter("estado = 'ACTIVA'");

                    b.ToTable("membresias_veterinaria", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Permisos.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_codigo_unico");

                    b.ToTable("permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Codigo = "veterinaria.ver",
                            Nombre = "Ver veterinaria"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Codigo = "veterinaria.editar",
                            Nombre = "Editar veterinaria"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Codigo = "personal.ver",
                            Nombre = "Ver personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Codigo = "personal.invitar",
                            Nombre = "Invitar personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Codigo = "personal.editar",
                            Nombre = "Editar personal"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Codigo = "personal.finalizar",
                            Nombre = "Finalizar personal"
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo_unico");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Codigo = "ADMINISTRADOR_VETERINARIA",
                            Estado = "ACTIVO",
                            Nombre = "Administrador de veterinaria"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Codigo = "VETERINARIO",
                            Estado = "ACTIVO",
                            Nombre = "Veterinario"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Codigo = "ASISTENTE",
                            Estado = "ACTIVO",
                            Nombre = "Asistente"
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000001"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000002"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-0000-0000-0000-000000000003"),
                            PermisoId = new Guid("22222222-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_verificado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<bool>("TelefonoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("telefono_verificado");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo_unico");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_publico");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Ruc")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPublico")
                        .IsUnique()
                        .HasDatabaseName("ix_veterinarias_codigo_publico_unico");

                    b.ToTable("veterinarias", (string)null);
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaRol", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", null)
                        .WithMany("Roles")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Veterinarias.Veterinaria", null)
                        .WithMany()
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.RolPermiso", b =>
                {
                    b.HasOne("SaaS.Veterinario.Domain.Permisos.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaaS.Veterinario.Domain.Roles.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Membresias.MembresiaVeterinaria", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SaaS.Veterinario.Domain.Roles.Rol", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
